baseURL = "http://yelling-at-trains.org/"
canonifyURLs = true
title = "Yelling at Trains"
languageCode = "en-us"
theme = "trains"
publishDir = "docs"

[blackfriday]
	hrefTargetBlank = true

[[menu.main]]
    name = "Archive"
    weight = -110
    identifier = "archive"
    url = "/"

[[menu.main]]
    name = "About"
    weight = -100
    identifier = "about"
    url = "/post/what-is-this"

[[menu.main]]
 	name = "Yell at me"
 	weight = -90
 	identifier = "contact"
 	url = "https://twitter.com/idreyn"

 [[menu.main]]
 	name = "Other writing"
 	weight = -80
 	identifier = "medium"
 	url = "https://medium.com/@idreyn"

 [[menu.main]]
 	name = "RSS"
 	weight = -80
 	identifier = "rss"
 	url = "/index.xml"
